### ISSUE TITLE
Use `configure-aws-credentials` instead of passing `secret_access_key`

### ISSUE THREAD

**Issue by vudiep411** [madolson/placeholderkv#1346]
**The problem/use-case that the feature addresses**
API calls to AWS need to be signed with credential information, so when you use one of the AWS SDKs or an AWS tool, you must provide it with AWS credentials and and AWS region. One way to do that in GitHub Actions is to use a repository secret with IAM credentials, but this doesn't follow [AWS security guidelines](https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds.html) on using long term creds.

**Description of the feature**
* First we need to set up OpenID Connect. [OpenID with AWS](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)
* Then Implement the workflow using [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file)

```
- name: Configure AWS Credentials for China region audience
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-3
        role-to-assume: arn:aws-cn:iam::123456789100:role/my-github-actions-role
```
By using this approach we can get rid off the secret keys needed to pass in and also organize the workflow
